version: '3.8'

services:
  backend:
    build: 
      context: Server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
  frontend:
    build: 
      context: Front-End
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  db:
    image: kwizera05/e-paydb:latest
    build: ./
    ports:
      - 27017:27017